Se agrega modelo Institution.
ignaciocapuccio/Relevamientos-ART pull request #10
Opened 2017-08-26 23:24 UTC by lgrula

Se agrega FK de visitas.
Se actualiza el index de visitas para que muestre la institucion

https://trello.com/c/aOZnuJP8/36-crear-modelo-de-instituci%C3%B3n

2017-08-26 23:25 UTC, lgrula commented
![](https://github.trello.services/images/mini-trello-icon.png) [Crear modelo de Institución](https://trello.com/c/aOZnuJP8/36-crear-modelo-de-instituci%C3%B3n)

2017-08-29 13:41 UTC, ghost requested changes

2017-08-29 13:41 UTC, ignaciocapuccio commented on app/models/institution.rb
> +  belongs_to :visit
Ojo con las relaciones... nunca podés tener dos `belongs_to` en una relación de modelos, ya que esta sentencia es la que determina "a nivel lógico" en qué modelo está la FK [fijate esto](http://requiremind.com/differences-between-has-one-and-belongs-to-in-ruby-on-rails/). De todas formas acá tenemos una relación `1 a N` donde una visita está bien que tenga una FK a institución, pero la inst tiene muchas visitas.

2017-08-29 13:41 UTC, ignaciocapuccio commented on app/models/institution.rb
> +  validates :name, :address, :city, :province, :number, :surface, :workers_count,
![screen shot 2017-08-29 at 10 27 31 am](https://user-images.githubusercontent.com/1652712/29823325-b0d0ecae-8ca4-11e7-8e2e-d78df23b6814.jpg)

Fijate que nos está faltando validar algunos datos!

2017-08-29 13:41 UTC, ignaciocapuccio commented on db/migrate/20170826215138_create_institutions.rb
> +    create_table :institutions do |t|
Fijate que faltaron algunos atributos

2017-08-29 13:41 UTC, ignaciocapuccio commented on db/seeds.rb
> +#institutions
Esto luego habría que actualizarlo en base a los campos que faltaban!

2017-08-29 13:41 UTC, ignaciocapuccio commented on spec/factories/institutions.rb
> +  factory :institution do
Lo mismo acá

2017-08-29 13:41 UTC, ignaciocapuccio commented on spec/factories/visits.rb
> +    association :institution, factory: :institution
acá poné solo `institution` y ya te lo reconoce y la genera

2017-08-29 13:41 UTC, ignaciocapuccio commented on spec/models/institution_spec.rb
> +describe Institution, type: :model do
Lo mismo acá, actualizar en base a los campos que faltaban

2017-08-31 18:51 UTC, closed without merging