Se agrega modelo Zona
ignaciocapuccio/Relevamientos-ART pull request #11
Opened 2017-08-29 02:33 UTC by lgrula

Se agrega FK de users

https://trello.com/c/LWg0tOr0/35-crear-modelo-de-zona

2017-08-29 02:36 UTC, lgrula commented
![](https://github.trello.services/images/mini-trello-icon.png) [Crear modelo de Zona](https://trello.com/c/LWg0tOr0/35-crear-modelo-de-zona)

2017-08-29 13:48 UTC, ghost requested changes
Fijate eso del schema! Yo siempre lo que suelo hacer cuando vuelvo a development dsp de un branch que modifiqué el schema es un `db:drop db:setup` para asegurarme que no me quede nada choteado.
Por otro lado ahí consulté al Slack, pero creo que la relación de Usuario con Zona es de 1 a N. Fijate el DER que está linkeado en el trello de Mapa de CU!

2017-08-29 13:48 UTC, ignaciocapuccio commented on db/schema.rb
> +  create_table "institutions", force: :cascade do |t|
Ojo! No se cómo estarás haciendo el switcheo de branches y demás (dsp lo vemos bien si querés) pero te están quedando modificaciones al schema de otros branches!

2017-08-31 22:10 UTC, ghost approved these changes

2017-08-31 22:11 UTC, merged