1er commint assignment
ignaciocapuccio/Relevamientos-ART pull request #17
Opened 2017-09-03 21:46 UTC by lgrula

## Summary

[Change!] Describe your feature, problems you had, notes, improvements and others.

## Screenshots

[Change!] Show the screenshots of the views you modified.

## Trello Card

[Change!] Link to the associated Trello card.

2017-09-04 04:08 UTC, ghost requested changes
Me agarraste con ganas de escribir viejo! 😬

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +    return render json: { error: 'Invalid params' }, status: :bad_request unless ind_valid_params?
Por qué cambiaste el nombre del método?

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +  end
Agregate un `private` después de este último método

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +        render json: visit, status: :not_found
`visit` es nulo... mejor hagamos `render_nothing_not_found` simplemente

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +      format.html { redirect_to visits_url, notice: 'Visit not founded' }
De acuerdo a como vamos a manejar las alertas por pantalla a partir de ahora, esto debería ser así:
```
flash[:alert] = 'No se encontró la visita'
format.html { redirect_to visits_url }
```

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +    return if assignment_validations
No me termina de convencer... en principio le cambiaría el nombre por algo más declarativo como por ej `invalid_assignment?`

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +  def assignment
la ruta está bien que sea /visits/:id/assignment, pero el método queda más declarativo si lo dejamos como `assign`. Te agrego el comentario en las rutas de cómo deberías ajustarlo ahí también

2017-09-04 04:08 UTC, ghost commented on config/routes.rb
> +    post :assignment, on: :member
Los `on: :member` los podés sacar. Es el comportamiento por default! Podés chequearlo haciendo el `rake routes`

Respecto al comentario de cambiar el nombre del método en el Controller, así debería quedar esta ruta definida:
`post :assignment, to: 'visits#assign'`

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +    return redirect_to visits_url, alert: @alert if @alert.present?
Esta forma de definir la alerta no se si va a funcionar... Probalo dsp de hacer el merge con lo que subí nuevo. Creo que lo vas a tener que hacer parecido al otro comentario que te hice más arriba.

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +    assignment_alert
A esto le pondría un nombre más declarativo. Si va a ser una función encargada de hacer validaciones algo como `validate_assigment` podría llegar a ser más claro

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +    @alert = 'User and Visit have different zones' unless visit.institution.zone.eql?(user.zone)
Estás sobreescribiendo el valor de @alert! No estás acumulando los posibles errores. Por otro lado, creo que algo como @errors sería más claro en general.

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +    return redirect_to visits_url, notice: 'Visita asignada' if visit.save
Estas dos alertas, fijate que seguro tmb haya que adaptarlas a lo nuevo. Chequealo local y cualquier cosa lo vemos juntos!

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +  def invalid_html_error(format, msg)
Esto dónde se usa?

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +  def revert_assignment
remove_assignment

2017-09-04 04:08 UTC, ghost commented on config/routes.rb
> +    post :revert_assignment, on: :member
`put :remotion, to: 'visits#remove_assignment'`

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +    return if revert_assignment_valid_params?
`invalid_remotion?`

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +    visit.revert_assignment
visit.remove_assigment

2017-09-04 04:08 UTC, ghost commented on app/controllers/visits_controller.rb
> +    return redirect_to visits_url, notice: 'Visita desasignada.' if visit.save
Lo mismo de antes. Chequear lo de las alertas/notices

2017-09-04 04:08 UTC, ignaciocapuccio commented on app/models/visit.rb
> +    return unless status_pending? && user.present? && user.role_preventor?
Extraete las condiciones a un método `valid_for_assigment?`

2017-09-04 04:08 UTC, ignaciocapuccio commented on app/models/visit.rb
> +  def revert_assignment
remove_assigment

2017-09-04 04:08 UTC, ignaciocapuccio commented on app/models/visit.rb
>    def validate_values
Desglocemos las condiciones así queda por qué no es válida la visita cuando se de el caso

2017-09-04 04:08 UTC, ignaciocapuccio commented
Agregate la descripción del PR y el linkeo de la card de trello si podés! 👍

2017-09-13 02:11 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    return render json: { error: 'Invalid params' }, status: :bad_request unless ind_valid_params?
Por que estos son invalid params del index, no del resto de los endpoint

2017-09-13 13:49 UTC, lgrula commented on config/routes.rb
> +    post :revert_assignment, on: :member
hecho

2017-09-13 13:49 UTC, lgrula commented on config/routes.rb
> +    post :assignment, on: :member
hecho

2017-09-13 13:49 UTC, lgrula commented on app/models/visit.rb
> +  def revert_assignment
hecho

2017-09-13 13:49 UTC, lgrula commented on app/models/visit.rb
> +    return unless status_pending? && user.present? && user.role_preventor?
hecho

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    visit.revert_assignment
hecho

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    return if revert_assignment_valid_params?
hecho

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +  def revert_assignment
hecho

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +  def invalid_html_error(format, msg)
Borrado. Me quedó viejo

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +  end
hecho

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    return if assignment_validations
Hecho

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +  def assignment
Hecho

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    @alert = 'User and Visit have different zones' unless visit.institution.zone.eql?(user.zone)
Hecho

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +        render json: visit, status: :not_found
Hecho

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    return redirect_to visits_url, notice: 'Visita desasignada.' if visit.save
Hecho

2017-09-13 13:49 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    assignment_alert
Hecho

2017-09-17 03:08 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    return redirect_to visits_url, notice: 'Visita asignada' if visit.save
No fue necesario.

2017-09-17 03:09 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    return redirect_to visits_url, alert: @alert if @alert.present?
no fue necesario.

2017-09-17 03:09 UTC, lgrula commented on app/controllers/visits_controller.rb
> +      format.html { redirect_to visits_url, notice: 'Visit not founded' }
hecho

2017-09-17 03:17 UTC, lgrula commented on app/models/visit.rb
>    def validate_values
hecho

2017-09-17 05:28 UTC, lgrula commented
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint de asignación de visita a usuario](https://trello.com/c/qZDBwTxT/56-endpoint-de-asignaci%C3%B3n-de-visita-a-usuario)

2017-09-17 07:18 UTC, ghost approved these changes
Mandale chamee

2017-09-17 07:18 UTC, ignaciocapuccio commented on app/controllers/visits_controller.rb
> +    return render json: { error: 'Invalid params' }, status: :bad_request unless ind_valid_params?
Oka, la prox podemos poner `index_valid_params?` para que sea bien declarativo por más que quede un poco más largo 🤓

2017-09-17 07:34 UTC, merged