Se agrega endpoint visit#complete
ignaciocapuccio/Relevamientos-ART pull request #22
Opened 2017-09-18 00:28 UTC by lgrula

validaciones:
-que se envíe la fecha de finalización por parámetro.
-que todas las tareas de la visita esten finalizadas.

El campo observaciones es opcional en el put

## Trello Card

https://trello.com/c/RAP9fxTq/51-endpoint-persistencia-formulario-de-visita

2017-09-18 00:28 UTC, lgrula commented
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint persistencia formulario de visita.](https://trello.com/c/RAP9fxTq/51-endpoint-persistencia-formulario-de-visita)

2017-09-23 22:48 UTC, ghost requested changes

2017-09-23 22:48 UTC, ignaciocapuccio commented on app/controllers/visits_controller.rb
> +    if visit.save
Si ya hiciste la desasignación en la línea anterior, qué estarías guardando acá? Si `remove_assignment` no está haciendo el "save", estaría mal. Tiene que hacerlo y en todo caso lo que haces es `if visit.remove_assignment ...`

2017-09-23 22:48 UTC, ignaciocapuccio commented on app/controllers/visits_controller.rb
> +    if visit.save
Acá lo mismo que para la desasignación

2017-09-23 22:48 UTC, ignaciocapuccio commented on app/controllers/visits_controller.rb
> +        complete_valid_params?
Si estás usando un mensaje específico a un parámetro, entonces quedaría mejor que el método sea algo como `complete_date_present?`

2017-09-23 22:48 UTC, ignaciocapuccio commented on app/controllers/visits_controller.rb
> +    if visit.save
Lo mismo que con los otros 2 endpoints

2017-09-23 22:48 UTC, ignaciocapuccio commented on app/controllers/visits_controller.rb
> +      render json: { error: visit.errors.full_messages.to_sentence }, status: :not_modified
En estos casos, al mobile retornemoslé un :unprocessable_entity (422)

2017-09-23 22:48 UTC, ignaciocapuccio commented on app/controllers/visits_controller.rb
>    def assignment_alert
No te parece que estas validaciones deberían estar en los modelos en lugar del controlador?

2017-09-23 22:48 UTC, ignaciocapuccio commented on app/controllers/visits_controller.rb
>    def ind_valid_params?
Este método al menos llamemoslo  `index_valid_params?`

2017-09-23 22:48 UTC, ignaciocapuccio commented on app/models/task.rb
> +  def completed?
Tiene sentido este método? Más allá de ser un bypass, le estamos dejando el mismo nombre casi

2017-09-23 22:48 UTC, ignaciocapuccio commented on app/models/visit.rb
> +    errors.add('error', 'La visita contiene tareas sin finalizar') unless all_tasks_completed?
Lo dejaría todo en una sola linea poniendo `if status_completed? && !all_tasks_completed?`

2017-09-23 22:48 UTC, ignaciocapuccio commented on app/models/visit.rb
> +    tasks.reject(&:completed?).empty?
Dibuje mago, dibuje!! 🌟

2017-09-23 22:48 UTC, ignaciocapuccio commented on config/routes.rb
> +    put :complete, to: 'visits#complete'
para dejarlo acorde a los otros endpoints, yo lo dejaría como `put :completion, to: `visits#complete`

2017-09-24 00:09 UTC, lgrula commented on config/routes.rb
> +    put :complete, to: 'visits#complete'
Hecho

2017-09-24 00:09 UTC, lgrula commented on app/models/visit.rb
> +    errors.add('error', 'La visita contiene tareas sin finalizar') unless all_tasks_completed?
Hecho

2017-09-24 00:09 UTC, lgrula commented on app/models/task.rb
> +  def completed?
Para mi si, encapsula el comportamiento en Task para saber si esta completa, sino desde afuera tendría que preguntar por el estado completado. Es similar al finished? que tenemos en visita.

2017-09-24 00:09 UTC, lgrula commented on app/controllers/visits_controller.rb
>    def ind_valid_params?
hecho

2017-09-24 00:09 UTC, lgrula commented on app/controllers/visits_controller.rb
> +      render json: { error: visit.errors.full_messages.to_sentence }, status: :not_modified
hecho.

2017-09-24 00:09 UTC, lgrula commented on app/controllers/visits_controller.rb
> +        complete_valid_params?
hecho

2017-09-24 00:09 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    if visit.save
hecho

2017-09-24 00:09 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    if visit.save
hecho

2017-09-24 00:09 UTC, lgrula commented on app/controllers/visits_controller.rb
> +    if visit.save
hecho

2017-09-24 00:09 UTC, lgrula commented on app/controllers/visits_controller.rb
>    def assignment_alert
hecho. Las puse afuera, por que quería validar antes de asignar. Pero lo pude resolver internamente

2017-10-01 22:32 UTC, ghost approved these changes

2017-10-01 22:33 UTC, merged