Se agrega endpoints persistencia de formularios.
ignaciocapuccio/Relevamientos-ART pull request #27
Opened 2017-10-29 05:08 UTC by lgrula

Se corrigen campos de resultados.
Se agrega info de tareas al detalle de visita

## Trello Card

https://trello.com/c/D6yMCoI8/50-endpoint-persistencia-formulario-capacitaci%C3%B3n
https://trello.com/c/4DOvMPGT/86-modificar-endpoint-de-detalle-de-visitas
https://trello.com/c/44MlgbQ1/84-revisar-modelo-formulario-de-capacitaci%C3%B3n-atributos-faltantes
https://trello.com/c/0ERrbJ3Z/87-endpoint-persistencia-formulario-rgrl
https://trello.com/c/Wmdc6xcA/88-endpoint-persistencia-formulario-rar

2017-10-29 16:16 UTC, ignaciocapuccio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint persistencia formulario capacitación](https://trello.com/c/D6yMCoI8/50-endpoint-persistencia-formulario-capacitaci%C3%B3n)

2017-10-29 16:17 UTC, ignaciocapuccio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modificar endpoint de detalle de visitas](https://trello.com/c/4DOvMPGT/86-modificar-endpoint-de-detalle-de-visitas)

2017-10-29 16:18 UTC, ignaciocapuccio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Revisar modelo formulario de capacitación atributos faltantes](https://trello.com/c/44MlgbQ1/84-revisar-modelo-formulario-de-capacitaci%C3%B3n-atributos-faltantes)

2017-10-29 16:18 UTC, ignaciocapuccio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint persistencia formulario RGRL](https://trello.com/c/0ERrbJ3Z/87-endpoint-persistencia-formulario-rgrl)

2017-10-29 16:18 UTC, ignaciocapuccio commented
![](https://github.trello.services/images/mini-trello-icon.png) [Endpoint persistencia formulario RAR](https://trello.com/c/Wmdc6xcA/88-endpoint-persistencia-formulario-rar)

2017-10-29 20:17 UTC, ghost requested changes
Fijate de agregar en alguno de los cap_result del seeds los nuevos atributos que cambiaron

2017-10-29 20:17 UTC, ghost commented on app/controllers/tasks_controller.rb
> +  rescue ActiveRecord::RecordInvalid => exception
Qué casos te caían en esta excepción por ejemplo?

2017-10-29 20:17 UTC, ghost commented on app/controllers/tasks_controller.rb
> +      raise 'task_type does not exists'
exist

2017-10-29 20:17 UTC, ghost commented on app/controllers/tasks_controller.rb
> +    case task.task_type_before_type_cast
Por qué cambiás el casteo para comparar acá? Si estás usando el objeto `task` con su propio atributo `task_type` no tendrías necesidad. Si dejás `case task.task_type`y luego haces por ej `when 'rgrl'` no te funciona?

2017-10-29 20:17 UTC, ghost commented on app/controllers/tasks_controller.rb
> +    Time.zone.parse(date)
👍

2017-10-29 20:17 UTC, ghost commented on app/controllers/tasks_controller.rb
> +    complete_process
`process_task_completion` creo que queda un poco más descriptivo

2017-10-29 20:17 UTC, ghost commented on app/controllers/tasks_controller.rb
> +      task_type_case
`create_task_result` me parece mejor

2017-10-29 20:17 UTC, ghost commented on app/controllers/tasks_controller.rb
> +    params[:working_men].each do |w|
`|incoming_worker|`

2017-10-29 20:17 UTC, ghost commented on app/controllers/tasks_controller.rb
> +      create_worker(rar_result, w)
create_worker(rar_result, incoming_worker)

2017-10-29 20:17 UTC, ghost commented on app/controllers/tasks_controller.rb
> +  def create_worker(rar_result, w)
create_worker(rar_result, incoming_worker)

2017-10-29 20:17 UTC, ghost commented on app/controllers/tasks_controller.rb
> +  def create_risks(w, worker)
create_risks(incoming_worker, worker)

2017-10-29 20:17 UTC, ghost commented on app/models/rar_result.rb
> -  validates :topic, :task, presence: true
No convendría agregar acá `contents`, `course_name` y `methodology`?

2017-10-29 20:17 UTC, ignaciocapuccio commented on app/serializers/visit_serializer.rb
> +             :completed_at, :observations, :tasks
Probá en lugar de haciéndolo así, en el renglón de abajo poniendo `has_many :tasks`, y quitando el método `tasks` de abajo

2017-10-29 20:17 UTC, ignaciocapuccio commented on db/schema.rb
> +    t.string   "topic",       null: false
topic lo van a mandar en cap_results?

2017-10-29 20:17 UTC, ignaciocapuccio commented on spec/factories/rar_results.rb
>    factory :rar_result do
Tiene sentido este factory? Si queda así entiendo que no lo usa nadie y habría que borrarlo

2017-10-29 21:50 UTC, lgrula commented on app/models/rar_result.rb
> -  validates :topic, :task, presence: true
Hecho

2017-10-29 21:50 UTC, lgrula commented on db/schema.rb
> +    t.string   "topic",       null: false
Hecho

2017-10-29 21:50 UTC, lgrula commented on spec/factories/rar_results.rb
>    factory :rar_result do
Hecho.

2017-10-29 22:03 UTC, lgrula commented on app/serializers/visit_serializer.rb
> +             :completed_at, :observations, :tasks
hecho

2017-10-29 22:04 UTC, lgrula commented on app/controllers/tasks_controller.rb
> +  def create_worker(rar_result, w)
hecho

2017-10-29 22:04 UTC, lgrula commented on app/controllers/tasks_controller.rb
> +  def create_risks(w, worker)
hecho

2017-10-29 22:05 UTC, lgrula commented on app/controllers/tasks_controller.rb
> +      create_worker(rar_result, w)
hecho

2017-10-29 22:05 UTC, lgrula commented on app/controllers/tasks_controller.rb
> +    params[:working_men].each do |w|
hecho

2017-10-29 22:06 UTC, lgrula commented on app/controllers/tasks_controller.rb
> +      task_type_case
hecho

2017-10-29 22:06 UTC, lgrula commented on app/controllers/tasks_controller.rb
> +      raise 'task_type does not exists'
hecho

2017-10-29 22:36 UTC, lgrula commented on app/controllers/tasks_controller.rb
> +    case task.task_type_before_type_cast
Hecho

2017-10-29 23:19 UTC, ghost approved these changes
Fijate eso solo que te comenté y metelo!

2017-10-29 23:19 UTC, ignaciocapuccio commented on app/models/rar_result.rb
> -  validates :topic, :task, presence: true
Fijate que lo metiste en el cap_result, pero no acá!

2017-11-02 00:16 UTC, lgrula commented on app/models/rar_result.rb
> -  validates :topic, :task, presence: true
pero el rarResult no tiene estos 3 campos. Solo saque el topic.

2017-11-04 20:11 UTC, merged