Pdfinformes
ignaciocapuccio/Relevamientos-ART pull request #37
Opened 2017-11-10 04:14 UTC by lgrula

Se agrega pantalla de informes para descargar los PDF.
Se agrega link al pdf de cada tarea dentro de la vista de detalle de visita.

## Screenshots
![captura de pantalla 2017-11-10 a las 1 09 21](https://user-images.githubusercontent.com/9040270/32642611-32c68256-c5de-11e7-8d9f-c6102d71ed85.png)
![captura de pantalla 2017-11-10 a las 1 09 02](https://user-images.githubusercontent.com/9040270/32642613-32f017f6-c5de-11e7-9756-6c9143bb2f9d.png)
![captura de pantalla 2017-11-10 a las 1 08 37](https://user-images.githubusercontent.com/9040270/32642614-3314c65a-c5de-11e7-8cc9-ecdc85052f65.png)

## Trello Card

https://trello.com/c/98Ox8nss/96-descargar-pdf-de-cada-tarea

2017-11-10 04:14 UTC, lgrula commented
![](https://github.trello.services/images/mini-trello-icon.png) [Descargar PDF de cada tarea.](https://trello.com/c/98Ox8nss/96-descargar-pdf-de-cada-tarea)

2017-11-11 19:19 UTC, ghost requested changes

2017-11-11 19:19 UTC, ignaciocapuccio commented on app/controllers/visits_controller.rb
> +  def report_index
Fijate que estás usando lo mismo que el método `completed_report_index`

2017-11-11 19:19 UTC, ignaciocapuccio commented on app/views/visits/show.html.erb
> +                        <a href= <%= @visit.tasks.rar.first.result.url_cloud %>><b> Relevamiento de Agentes de Riesgo</b></a><br />
falta el target="_blank"

2017-11-11 19:19 UTC, ignaciocapuccio commented on app/views/visits/show.html.erb
> +                        <a href= <%= @visit.tasks.cap.first.result.url_cloud %>><b> Capacitación</b></a><br />
falta el target="_blank"

2017-11-12 01:22 UTC, ghost approved these changes

2017-11-12 01:24 UTC, merged